import { createClient } from '@supabase/supabase-js';
import { esc, numberValue, safeUrl, errorText } from './domain.js';

const db = createClient('https://ddxzgkqjorqlfotfhiok.supabase.co', 'sb_publishable_aGfp3wm90eWyZq6XErKBIQ_Ro86Ny-U');
const $ = s => document.querySelector(s);
const root = $('#app');
let user = null, campaigns = [], campaign = null, chars = [], members = [], investigators = [], sessions = [], results = [], notes = [], events = [], invites = [];
let page = 'overview', chosen = null, busy = false, dirty = false, loadVersion = 0, recovery = location.hash.includes('type=recovery');
let pendingInvite = new URLSearchParams(location.search).get('invite') || sessionStorage.getItem('arkham.pendingInvite') || '';
if (pendingInvite) sessionStorage.setItem('arkham.pendingInvite', pendingInvite);
const currentSession = () => sessions[0];
const currentInvestigator = () => investigators.find(i => i.user_id === user?.id && i.active);
const isOwner = () => campaign?.owner_id === user?.id;
const isGM = () => currentSession()?.gm_id === user?.id;
const memberName = id => members.find(m => m.user_id === id)?.name || 'Korábbi játékos';
const character = i => chars.find(c => c.code === i?.character_code);
const date = d => new Date(d).toLocaleString('hu-HU', {dateStyle:'medium',timeStyle:'short'});
const styles = {'Őrző':'','Kutató':'seeker','Misztikus':'mystic','Túlélő':'survivor','Zsivány':'rogue','Semleges':'neutral','Kutató / Misztikus':'seeker'};
const avatar = i => {const c=character(i);return `<div class="avatar ${styles[c?.class] || ''}" aria-hidden="true">${esc(c?.name.split(' ').map(s=>s[0]).slice(0,2).join('') || '?')}</div>`;};
const head = (k,t,sub='',actions='') => `<div class="eyebrow">${esc(k)}</div><div class="heading"><div><h1>${esc(t)}</h1><p class="muted">${esc(sub)}</p></div><div class="actions">${actions}</div></div>`;
const button = (action,text,primary=false,disabled=false) => `<button type="button" data-action="${action}" class="${primary?'primary':'ghost'}" ${disabled?'disabled':''}>${text}</button>`;
const field = (name,label,value='',type='text',attrs='') => `<div class="field"><label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" value="${esc(value)}" ${attrs}></div>`;
const textarea = (name,label,value='',max=10000) => `<div class="field full"><label for="${name}">${label}</label><textarea id="${name}" name="${name}" maxlength="${max}">${esc(value)}</textarea></div>`;
const actionNames={create_campaign:'Kampány létrehozva',join_campaign:'Új csapattag',create_invite:'Meghívó készült',revoke_invite:'Meghívó visszavonva',transfer_owner:'Kampánygazda megváltozott',choose_character:'Nyomozó kiválasztva',save_investigator:'Nyomozó adatlapja frissítve',start_session:'Alkalom elindítva',save_result:'Személyes eredmény rögzítve',save_common:'Közös eredmény mentve',transfer_gm:'Játékmesteri szerep átadva',add_note:'Közös bejegyzés',close_session:'Alkalom lezárva',close_campaign:'Kampány lezárva'};

function notify(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#toast').style.display='none',6000);}
function showError(error){const message=errorText(error);const el=$('#modal[open] .error') || $('.content .error') || $('.auth .error');if(el){el.textContent=message;el.hidden=false;}notify(message);}
function setBusy(value){busy=value;document.querySelectorAll('button[type=submit],dialog[open] button').forEach(b=>{if(value){b.dataset.wasDisabled=String(b.disabled);b.disabled=true;}else if(b.dataset.wasDisabled!==undefined){b.disabled=b.dataset.wasDisabled==='true';delete b.dataset.wasDisabled;}});}
async function perform(fn){if(busy)return;setBusy(true);try{await fn();}catch(e){showError(e);}finally{setBusy(false);}}
function modal(html){$('#modal').innerHTML=`<div class="error" role="alert" hidden></div>${html}`;$('#modal').showModal();$('#modal').querySelectorAll('[data-dismiss]').forEach(b=>b.onclick=()=>$('#modal').close());}
function confirmAction(title,body,fn,label='Megerősítés'){modal(`<h2>${esc(title)}</h2><div>${body}</div><div class="actions"><button type="button" id="confirm" class="primary">${label}</button><button type="button" data-dismiss>Mégse</button></div>`);$('#confirm').onclick=()=>perform(async()=>{await fn();$('#modal').close();});}
async function rpc(action,data={},cid=campaign?.id){const {data:result,error}=await db.rpc('arkham_action',{p_action:action,p_campaign:cid||null,p_data:data});if(error)throw error;return result;}
async function mutation(action,data={},message='A változások mentve.'){await rpc(action,data);dirty=false;await loadCampaign(campaign.id);notify(message);}
function nav(next,id=null){if(dirty){confirmAction('Nem mentett változások','<p>Elhagyod az oldalt a módosítások mentése nélkül?</p>',async()=>{dirty=false;page=next;chosen=id;render();},'Oldal elhagyása');return;}page=next;chosen=id;render();window.scrollTo(0,0);}
async function table(name,cid,order){let q=db.from('arkham_'+name).select('*').eq('campaign_id',cid);if(order)q=q.order(order,{ascending:false});const {data,error}=await q;if(error)throw error;return data;}
async function loadCampaign(id){const version=++loadVersion;const list=await db.from('arkham_campaigns').select('*').order('created_at',{ascending:false});if(list.error)throw list.error;if(version!==loadVersion)return;campaigns=list.data;const next=campaigns.find(c=>c.id===id);if(!next){campaign=null;page='campaigns';render();return;}
 const loaded=await Promise.all([table('members',id),table('investigators',id),table('sessions',id,'number'),table('results',id),table('journal',id,'created_at'),table('events',id,'created_at'),table('invites',id)]);
 if(version!==loadVersion)return;campaign=next;[members,investigators,sessions,results,notes,events,invites]=loaded;localStorage.setItem('arkham.selectedCampaign',id);render();}
async function loadAccount(){const version=++loadVersion;const [a,b]=await Promise.all([db.from('arkham_campaigns').select('*').order('created_at',{ascending:false}),db.from('arkham_characters').select('*').order('name')]);if(a.error||b.error)throw a.error||b.error;if(version!==loadVersion)return;campaigns=a.data;chars=b.data;
 const selected=localStorage.getItem('arkham.selectedCampaign');if(!pendingInvite&&campaigns.length)await loadCampaign(campaigns.some(c=>c.id===selected)?selected:campaigns[0].id);else{campaign=null;page='campaigns';render();}}

function render(){if(!user){authView();return;}if(recovery){passwordView();return;}root.innerHTML=`<div class="shell"><aside><div class="brand"><span class="brand-mark">◇</span>ARKHAM</div><div class="brand-sub">Kampánynapló</div><nav class="nav" aria-label="Főmenü">${[['campaigns','Kampányaim'],...(campaign?[['overview','Kampány'],['investigator','Saját nyomozó'],['session','Játékalkalom'],['journal','Közös napló'],['history','Előzmények'],['team','Csapat és meghívók']]:[])].map(([p,t])=>`<button data-nav="${p}" class="${page===p?'active':''}" ${page===p?'aria-current="page"':''}>${t}</button>`).join('')}</nav><div class="aside-bottom"><strong>${esc(campaign?memberName(user.id):user.user_metadata?.display_name||'Nyomozó')}</strong><p>${esc(user.email)}</p>${button('logout','Kijelentkezés')}</div></aside><main><header class="topbar"><span>${esc(campaign?.name||'A kampányaid')}</span><div class="profile"><span>${esc(campaign?memberName(user.id):'Bejelentkezve')}</span>${isGM()?'<span class="pill gold">Játékmester</span>':''}${button('refresh','Frissítés')}${button('logout','Kilépés')}</div></header><div class="content"><div class="error" role="alert" hidden></div>${page==='campaigns'?campaignsView():page==='overview'?overviewView():page==='investigator'?investigatorView():page==='session'?sessionView():page==='journal'?journalView():page==='team'?teamView():historyView()}<p class="footer-note">A mentett adatok a csapattársak számára is elérhetők. Mások frissítéseit a Frissítés gombbal töltheted be.</p></div></main></div>`;
 bind();appendDeleteButton();}
function authView(mode='login'){root.innerHTML=`<main class="auth"><div class="brand"><span class="brand-mark">◇</span>ARKHAM</div><p class="eyebrow">Kampánynapló</p><section class="panel"><h1>${mode==='register'?'Csatlakozz a történethez':'Üdv újra, nyomozó!'}</h1><p class="muted">${pendingInvite?'Kampánymeghívó vár rád. Jelentkezz be, vagy hozz létre fiókot.':'Lépj be a saját nyomozóidhoz és a társaság kampányaihoz.'}</p><div class="error" role="alert" hidden></div><form id="auth-form">${mode==='register'?field('display_name','Játékosnév','','text','required maxlength="80" autocomplete="nickname"'):''}${field('email','E-mail-cím','','email','required autocomplete="email"')}${field('password','Jelszó','','password',`required ${mode==='register'?'minlength="8" autocomplete="new-password"':'autocomplete="current-password"'}`)}<button type="submit" class="primary">${mode==='register'?'Fiók létrehozása':'Belépés'}</button></form><div class="actions" style="margin-top:20px"><button id="auth-switch" class="ghost">${mode==='register'?'Már van fiókom':'Új fiókot szeretnék'}</button><button id="forgot" class="ghost">Elfelejtett jelszó</button></div><p class="muted" style="font-size:14px;margin:20px 0 0">A kampányok csak a meghívott csapattagok számára láthatók.</p></section></main>`;
 $('#auth-switch').onclick=()=>authView(mode==='register'?'login':'register');$('#forgot').onclick=forgotPassword;
 $('#auth-form').onsubmit=e=>{e.preventDefault();perform(async()=>{const f=new FormData(e.target);let response;if(mode==='register'){response=await db.auth.signUp({email:f.get('email').trim(),password:f.get('password'),options:{data:{display_name:f.get('display_name').trim()},emailRedirectTo:location.origin+location.pathname}});}else response=await db.auth.signInWithPassword({email:f.get('email').trim(),password:f.get('password')});if(response.error)throw response.error;
 if(response.data.session){user=response.data.user;await loadAccount();}else{authView();notify('Ha a regisztráció sikeres, a megerősítő levél hamarosan megérkezik. Erősítsd meg az e-mail-címedet, majd lépj be.');}});};}
function forgotPassword(){modal(`<h2>Új jelszó igénylése</h2><p class="muted">E-mailben küldünk jelszó-visszaállítási linket.</p><form id="reset-form">${field('reset_email','E-mail-cím','','email','required autocomplete="email"')}<div class="actions"><button type="submit" class="primary">Link kérése</button><button type="button" data-dismiss>Mégse</button></div></form>`);$('#reset-form').onsubmit=e=>{e.preventDefault();perform(async()=>{const {error}=await db.auth.resetPasswordForEmail(new FormData(e.target).get('reset_email').trim(),{redirectTo:location.origin+location.pathname});if(error)throw error;$('#modal').close();notify('Ha a fiók létezik, elküldtük a visszaállítási linket.');});};}
function passwordView(){root.innerHTML=`<main class="auth"><section class="panel"><h1>Új jelszó</h1><div class="error" role="alert" hidden></div><form id="password-form">${field('new_password','Új jelszó','','password','required minlength="8" autocomplete="new-password"')}${field('repeat_password','Jelszó ismétlése','','password','required minlength="8" autocomplete="new-password"')}<button type="submit" class="primary">Új jelszó mentése</button></form></section></main>`;$('#password-form').onsubmit=e=>{e.preventDefault();perform(async()=>{const f=new FormData(e.target);if(f.get('new_password')!==f.get('repeat_password'))throw Error('A két jelszó nem egyezik.');const {error}=await db.auth.updateUser({password:f.get('new_password')});if(error)throw error;recovery=false;await loadAccount();notify('A jelszó megváltozott.');});};}
function campaignsView(){return head('Közös történetek','Kampányaim','Indíts új történetet, vagy csatlakozz meghívóval.',button('new-campaign','Új kampány',true))+`${pendingInvite?`<section class="panel" style="margin-bottom:24px"><h2>Meghívó érkezett</h2><form id="join-form">${field('player_name','Játékosneved',user.user_metadata?.display_name||'','text','required maxlength="80"')}${field('token','Meghívókód',pendingInvite,'text','required')}<div class="actions"><button type="submit" class="primary">Csatlakozás a kampányhoz</button>${button('dismiss-invite','Meghívó elrejtése')}</div></form></section>`:''}<div class="catalog">${campaigns.map(c=>`<article class="panel"><span class="pill ${c.closed?'':'gold'}">${c.closed?'Lezárva':'Aktív kampány'}</span><h2 style="margin-top:18px">${esc(c.name)}</h2><p class="muted">${esc(c.campaign_type)} · ${esc(c.difficulty)}</p><button data-campaign="${c.id}" class="primary">Kampány megnyitása ↗</button></article>`).join('')||'<section class="panel empty"><h2>Még nincs kampányod.</h2><p>Készíts egyet a társaságnak, vagy nyisd meg a kampánygazda meghívólinkjét.</p></section>'}</div><section class="panel" style="margin-top:24px"><h2>Van meghívókódod?</h2><form id="manual-invite">${field('invite','Meghívólink vagy kód','','text','required')}<button type="submit" class="ghost">Meghívó megnyitása</button></form></section>`;}
function overviewView(){const s=currentSession(),i=currentInvestigator();return head(campaign.campaign_type,campaign.name,campaign.difficulty+(campaign.closed?' · Lezárt kampány':''))+`<section class="campaign"><div><span class="pill ${s?.closed?'':'gold'}">${s?s.closed?'LEGUTÓBBI ALKALOM':'AKTUÁLIS ALKALOM':'A TÖRTÉNET KEZDETE'}</span><h2>${esc(s?.title||'Készüljetek az első alkalomra')}</h2><p class="muted">${s?'Vezessétek a nyomozók állapotát és a közös döntéseket.':'Hívjátok meg a csapatot, és válasszátok ki a nyomozókat.'}</p>${s?`<div class="meta"><span>${s.number}. alkalom</span><span>Játékmester: ${esc(memberName(s.gm_id))}</span><span>${results.filter(r=>r.session_id===s.id&&r.submitted).length}/${results.filter(r=>r.session_id===s.id).length} eredmény mentve</span></div>`:''}</div><div class="actions">${s?button('session','Alkalom megnyitása ↗',true):button('start','Első alkalom indítása',true,!isOwner()||campaign.closed)}</div></section><div class="stats"><div class="stat"><strong>${members.length}</strong><span>csapattag</span></div><div class="stat"><strong>${i?i.earned-i.spent:'—'}</strong><span>saját elkölthető XP</span></div><div class="stat"><strong>${sessions.filter(s=>s.closed).length}</strong><span>lezárt alkalom</span></div></div><div class="columns"><section><div class="section-title"><h2>A nyomozócsapat</h2>${button('team','Csapat ↗')}</div>${teamCards()}</section><section class="panel"><h2>A napló margóján</h2><p class="note" style="white-space:pre-wrap">${esc(notes[0]?.body||'Még nincs közös bejegyzés. Az első játékalkalommal kezdődik a történet.')}</p>${button('journal','Közös napló ↗')}</section></div>`;}
function teamCards(){return `<div class="investigators">${members.map(m=>{const i=investigators.find(x=>x.active&&x.user_id===m.user_id);return `<article class="person ${m.user_id===user.id?'mine':''}">${avatar(i)}<div class="person-info"><h3>${esc(i?character(i)?.name:'Még nincs nyomozó')}</h3><small>${esc(m.name)}${m.user_id===user.id?' · Te':''}${m.user_id===currentSession()?.gm_id?' · Játékmester':''}</small></div>${i?`<div class="xp">${i.earned-i.spent}<small>XP maradt</small></div><button class="small ghost" data-person="${i.id}" aria-label="${esc(character(i)?.name)} adatlapja">↗</button>`:m.user_id===user.id?button('choose','Választás',false,campaign.closed||!!(currentSession()&&!currentSession().closed)):''}</article>`;}).join('')}</div>`;}
function investigatorView(){const i=investigators.find(x=>x.id===chosen)||currentInvestigator(),own=i?.user_id===user.id,editable=own&&i.active&&!campaign.closed,c=character(i);if(!i)return head('Nyomozói dosszié','Válassz nyomozót','A kiválasztott karakter ehhez a kampányhoz tartozik.')+`<section class="panel"><p>${currentSession()&&!currentSession().closed?'Az aktuális alkalom már elkezdődött. A következő előtt választhatsz nyomozót.':'Válassz a nyomozók közül, mielőtt elkezdődik az alkalom.'}</p>${button('choose','Karakter kiválasztása',true,campaign.closed||!!(currentSession()&&!currentSession().closed))}</section>`;
 return head('Nyomozói dosszié',own?'Saját nyomozó':`${memberName(i.user_id)} nyomozója`,i.active?'A nyomozó állapota ebben a kampányban.':'Archivált nyomozó · Az adatok megmaradtak.')+`<div class="columns"><section class="panel"><div class="detail-head">${avatar(i)}<div><span class="eyebrow">${esc(c?.class)}</span><h2>${esc(c?.name)}</h2><span class="muted">${esc(c?.subtitle)}</span></div></div>${editable?button('choose','Karaktercsere',false,!!(currentSession()&&!currentSession().closed)):''}<form id="investigator-form" data-id="${i.id}" data-revision="${i.revision}" style="margin-top:24px"><fieldset ${editable?'':'disabled'}><div class="form-grid">${field('earned','Összes megszerzett XP',i.earned,'number','disabled')}${field('spent','Összes elköltött XP',i.spent,'number',`required min="0" max="${i.earned}" step="1"`)}${field('physical','Fizikai trauma összesen',i.physical,'number','required min="0" max="999" step="1"')}${field('mental','Mentális trauma összesen',i.mental,'number','required min="0" max="999" step="1"')}${textarea('status','Állapotok',i.status,2000)}${field('deck','Pakli linkje',i.deck,'url','maxlength="2000"')}${textarea('notes','Személyes jegyzetek',i.notes)}</div>${editable?'<button type="submit" class="primary">Adatlap mentése</button>':''}</fieldset></form></section><section><div class="panel"><span class="eyebrow">Fejlődés</span><div class="stat"><strong>${i.earned-i.spent}</strong><span>elkölthető XP</span></div><p class="muted">A kapott XP-t az alkalom eredményeinél rögzítsd. Az adatlapon a már elköltött XP és az aktuális traumák javíthatók.</p>${safeUrl(i.deck)?`<a class="button-link" href="${esc(i.deck)}" target="_blank" rel="noopener noreferrer">Pakli megnyitása ↗</a>`:''}</div>${investigators.filter(x=>!x.active&&x.user_id===i.user_id).length?`<div class="panel" style="margin-top:20px"><h3>Korábbi nyomozók</h3>${investigators.filter(x=>!x.active&&x.user_id===i.user_id).map(x=>`<p><button class="ghost" data-person="${x.id}">${esc(character(x)?.name)} ↗</button></p>`).join('')}</div>`:''}</section></div>`;}
function sessionView(){const s=currentSession();if(!s)return head('Játékalkalmak','Az első alkalom előtt','A kampánygazda indíthatja el az alkalmat.')+`<section class="panel">${button('start','Alkalom indítása',true,!isOwner()||campaign.closed)}</section>`;
 const r=results.find(x=>x.session_id===s.id&&x.user_id===user.id),participants=results.filter(x=>x.session_id===s.id),complete=participants.every(x=>x.submitted)&&s.resolution.trim(),editable=!s.closed&&!campaign.closed;
 return head(`${s.number}. játékalkalom`,s.title,s.closed?'Az alkalom eredményei véglegesek.':'Az eredmények lezárásig javíthatók.',`<span class="pill ${s.closed?'':'gold'}">${s.closed?'Lezárva':'Nyitott alkalom'}</span>`)+`<div class="columns"><section><div class="panel"><div class="section-title"><h2>Saját eredményeim</h2>${r?`<span class="pill ${r.submitted?'':'gold'}">${r.submitted?'Mentve':'Kitöltésre vár'}</span>`:''}</div>${r?`<p class="muted">${esc(character(investigators.find(i=>i.id===r.investigator_id))?.name)}</p><form id="result-form" data-revision="${r.revision}"><fieldset ${editable?'':'disabled'}><div class="form-grid">${field('xp','Ezen az alkalmon kapott XP',r.xp,'number','required min="0" max="99" step="1"')}${field('physical','Új fizikai trauma',r.physical,'number','required min="0" max="99" step="1"')}${field('mental','Új mentális trauma',r.mental,'number','required min="0" max="99" step="1"')}${textarea('note','Az alkalom személyes jegyzete',r.note)}</div>${editable?'<button type="submit" class="primary">Eredmények áttekintése</button>':''}</fieldset></form>`:'<p class="muted">Ehhez az alkalomhoz nem tartozik résztvevő nyomozód. A következő alkalom előtt választhatsz karaktert.</p>'}</div><div class="panel" style="margin-top:22px"><h2>Közös eredmény</h2>${isGM()&&editable?`<form id="common-form" data-revision="${s.revision}">${field('resolution','Végkifejlet / eredmény',s.resolution,'text','required maxlength="2000"')}${textarea('note','Közös döntések, változások',s.note)}<button type="submit" class="primary">Közös eredmény mentése</button></form>`:`<p>${esc(s.resolution||'Még nincs rögzített közös eredmény.')}</p><p style="white-space:pre-wrap" class="muted">${esc(s.note)}</p><small class="muted">Játékmester: ${esc(memberName(s.gm_id))}</small>`}</div></section><section><div class="panel"><h2>Az alkalom felelőse</h2><p>${esc(memberName(s.gm_id))} · Játékmester</p>${editable&&(isGM()||isOwner())?button('gm','Szerep átadása'):''}<h3 style="margin-top:28px">Csapat visszajelzései</h3><ul class="checklist">${participants.map(x=>`<li><span>${esc(memberName(x.user_id))}</span><span>${x.submitted?'✓ Mentve':'Még hátravan'}</span></li>`).join('')}</ul>${editable?`<p class="muted">A játékmester zárhatja le, ha minden eredmény megvan.</p>${button('close-session','Alkalom lezárása',true,!isGM()||!complete)}`:button('start','Következő alkalom',true,campaign.closed||!(isOwner()||isGM()))}</div><div class="panel" style="margin-top:22px"><h3>Korábbi alkalmak</h3>${sessions.filter(x=>x.id!==s.id).map(x=>`<details><summary>${x.number}. ${esc(x.title)}</summary><p>${esc(memberName(x.gm_id))} · ${esc(x.resolution)}</p><p style="white-space:pre-wrap">${esc(x.note)}</p>${results.filter(r=>r.session_id===x.id).map(r=>`<p>${esc(memberName(r.user_id))}: +${r.xp} XP, +${r.physical} fizikai / +${r.mental} mentális trauma<br>${esc(r.note)}</p>`).join('')}</details>`).join('')||'<p class="muted">Még nincs korábbi alkalom.</p>'}</div></section></div>`;}
function journalView(){return head('Közös emlékezet','Kampánynapló','A csapat döntései és a történet következményei.')+`<div class="columns"><section class="history">${notes.map(n=>`<article class="panel"><span class="eyebrow">${esc(memberName(n.author_id))} · ${esc(date(n.created_at))}</span><p style="margin-top:18px;white-space:pre-wrap">${esc(n.body)}</p></article>`).join('')||'<p class="empty">Még nincs közös bejegyzés.</p>'}</section><section class="panel" style="align-self:start"><h2>Új bejegyzés</h2>${isGM()&&!currentSession()?.closed&&!campaign.closed?`<form id="note-form">${textarea('body','Mit jegyezzen meg a csapat?')}<button type="submit" class="primary">Bejegyzés mentése</button></form>`:'<p class="muted">A nyitott alkalom játékmestere írhat új közös bejegyzést.</p>'}</section></div>`;}
function teamView(){return head('A társaság','Csapat és meghívók',`Kampánygazda: ${memberName(campaign.owner_id)} · ${members.length}/4 csapattag`)+`<div class="columns"><section>${teamCards()}</section><section class="panel"><h2>Kampány kezelése</h2>${isOwner()&&!campaign.closed?`<p class="muted">A meghívó 7 napig érvényes. A link birtokosa belépés után csatlakozhat.</p>${button('invite','Meghívólink készítése',true)}<div style="margin-top:22px">${invites.filter(i=>!i.revoked&&new Date(i.expires_at)>new Date()).map(i=>`<div class="invite-item"><label>Meghívó · lejár: ${esc(date(i.expires_at))}</label><input readonly aria-label="Meghívólink" value="${esc(inviteUrl(i.token))}"><button class="small ghost" data-revoke="${i.token}">Meghívó visszavonása</button></div>`).join('')}</div><hr><div class="actions">${button('owner','Kampánygazda átadása',false,members.length<2)}${button('close-campaign','Kampány lezárása',false,!!(currentSession()&&!currentSession().closed))}</div>`:'<p class="muted">A meghívókat és a kampánygazdai szerepet a kampánygazda kezeli.</p>'}</section></div>`;}
function eventSummary(e){const d=e.detail;if(e.action==='save_result')return `${d.after?.xp??0} kapott XP · ${d.after?.physical??0} fizikai / ${d.after?.mental??0} mentális trauma`;if(e.action==='transfer_gm'||e.action==='transfer_owner')return `${memberName(d.from)} → ${memberName(d.to)}`;if(e.action==='choose_character')return character(d.current)?.name||'';if(e.action==='save_investigator')return `${(d.after?.earned||0)-(d.after?.spent||0)} elkölthető XP`;return d.title||d.body||d.resolution||'';}
function historyView(){return head('Minden változásnak nyoma van','Előzmények','A mentett módosítások időrendben.')+`<div class="history">${events.map(e=>`<article class="panel"><span class="eyebrow">${esc(date(e.created_at))} · ${esc(memberName(e.actor_id))}</span><h3 style="margin-top:14px">${actionNames[e.action]||esc(e.action)}</h3><p class="muted">${esc(eventSummary(e))}</p>${e.detail.before||e.detail.after||e.detail.previous?`<details><summary>Változás részletei</summary>${eventDetails(e)}</details>`:''}</article>`).join('')||'<p class="empty">Még nincs változás.</p>'}</div>`;}
const inviteUrl = token => `${location.origin}${location.pathname}?invite=${encodeURIComponent(token)}`;

function newCampaign(){modal(`<h2>Új kampány</h2><form id="campaign-form">${field('name','A kampányotok neve','','text','required maxlength="120" placeholder="Például: Vasárnapi nyomozók"')}${field('campaign_type','Kampány / történet','The Night of the Zealot','text','required maxlength="120"')}${field('player_name','Játékosneved',user.user_metadata?.display_name||'','text','required maxlength="80"')}<div class="field"><label for="difficulty">Nehézség</label><select id="difficulty" name="difficulty"><option>Könnyű</option><option selected>Normál</option><option>Nehéz</option><option>Extrém</option></select></div><div class="actions"><button type="submit" class="primary">Kampány létrehozása</button><button type="button" data-dismiss>Mégse</button></div></form>`);$('#campaign-form').onsubmit=e=>{e.preventDefault();perform(async()=>{const data=await rpc('create_campaign',Object.fromEntries(new FormData(e.target)),null);page='overview';await loadCampaign(data.campaign_id);$('#modal').close();notify('A kampány elkészült. Hívd meg a csapatot!');});};}
function chooseCharacter(){if(campaign.closed||currentSession()&&!currentSession().closed){notify('Nyomozót két játékalkalom között választhatsz.');return;}modal(`<div class="section-title"><h2>Válassz nyomozót</h2><button type="button" data-dismiss aria-label="Bezárás">✕</button></div><p class="muted">A normál kampányok Hall of Arkham-listájának 64 nyomozója közül választhatsz. Karaktercserekor a régi adatlap megmarad, az új 0 XP-vel indul.</p><div class="form-grid">${field('search','Keresés','','search')}<div class="field"><label for="class">Kaszt</label><select id="class"><option value="">Minden kaszt</option>${[...new Set(chars.map(c=>c.class))].map(c=>`<option>${esc(c)}</option>`).join('')}</select></div></div><div id="catalog" class="catalog"></div>`);
 const draw=()=>{$('#catalog').innerHTML=chars.filter(c=>c.name.toLocaleLowerCase().includes($('#search').value.toLocaleLowerCase())&&(!$('#class').value||c.class===$('#class').value)).map(c=>{const used=investigators.find(i=>i.active&&i.character_code===c.code);return `<button type="button" data-character="${esc(c.code)}" class="character" ${used?'disabled':''}>${avatar({character_code:c.code})}<strong>${esc(c.name)}</strong><small>${esc(c.class)} · ${esc(c.subtitle)}</small><span class="pill ${used?'':'gold'}">${used?used.user_id===user.id?'Jelenlegi nyomozó':'Foglalt':'Kiválasztás'}</span></button>`;}).join('')||'<p>Nincs ilyen nyomozó.</p>';document.querySelectorAll('[data-character]').forEach(b=>b.onclick=()=>{const code=b.dataset.character;confirmAction('Nyomozó kiválasztása',`<p>${esc(chars.find(c=>c.code===code)?.name)} lesz az aktív nyomozód. ${currentInvestigator()?'A jelenlegi adatlap archiválódik.':''}</p>`,async()=>{await mutation('choose_character',{character_code:code});chosen=null;page='investigator';render();},'Kiválasztás');});};$('#search').oninput=draw;$('#class').onchange=draw;draw();}
function startSession(){modal(`<h2>Új játékalkalom</h2><p class="muted">A jelenlegi aktív nyomozók lesznek a résztvevők. A játékmester saját nyomozó nélkül is vezetheti az alkalmat.</p><form id="start-form">${field('title','Forgatókönyv neve','','text','required maxlength="160"')}${memberSelect('gm_id','Játékmester',currentSession()?.gm_id||user.id)}<div class="actions"><button type="submit" class="primary">Alkalom indítása</button><button type="button" data-dismiss>Mégse</button></div></form>`);$('#start-form').onsubmit=e=>{e.preventDefault();perform(async()=>{await mutation('start_session',Object.fromEntries(new FormData(e.target)));page='session';render();$('#modal').close();});};}
function memberSelect(name,label,selected){return `<div class="field"><label for="${name}">${label}</label><select id="${name}" name="${name}">${members.map(m=>`<option value="${m.user_id}" ${selected===m.user_id?'selected':''}>${esc(m.name)}</option>`).join('')}</select></div>`;}
function transferRole(owner=false){const s=currentSession();modal(`<h2>${owner?'Kampánygazda':'Játékmester'} átadása</h2><p class="muted">Az eddigi adatok megmaradnak. Az új felelős a mentés után kapja meg a szerepet.</p><form id="transfer-form">${memberSelect('user_id','Új felelős',owner?campaign.owner_id:s.gm_id)}<div class="actions"><button type="submit" class="primary">Szerep átadása</button><button type="button" data-dismiss>Mégse</button></div></form>`);$('#transfer-form').onsubmit=e=>{e.preventDefault();perform(async()=>{const id=new FormData(e.target).get('user_id');await mutation(owner?'transfer_owner':'transfer_gm',owner?{user_id:id}:{session_id:s.id,gm_id:id,revision:s.revision});$('#modal').close();});};}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));document.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>nav('investigator',b.dataset.person));document.querySelectorAll('[data-campaign]').forEach(b=>b.onclick=()=>perform(async()=>{page='overview';await loadCampaign(b.dataset.campaign);}));
 document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));document.querySelectorAll('[data-revoke]').forEach(b=>b.onclick=()=>confirmAction('Meghívó visszavonása','<p>A linkkel ezután nem lehet újonnan csatlakozni. A meglévő tagok maradnak.</p>',()=>mutation('revoke_invite',{token:b.dataset.revoke})));
 document.querySelectorAll('form input,form textarea,form select').forEach(el=>el.addEventListener('input',()=>dirty=true));
 const form=(id,fn)=>{if($(id))$(id).onsubmit=e=>{e.preventDefault();perform(()=>fn(new FormData(e.target),e.target));};};
 form('#investigator-form',async(f,el)=>{await mutation('save_investigator',{id:el.dataset.id,revision:Number(el.dataset.revision),spent:numberValue(f.get('spent'),0,99999),physical:numberValue(f.get('physical'),0,999),mental:numberValue(f.get('mental'),0,999),status:f.get('status').trim(),notes:f.get('notes').trim(),deck:f.get('deck').trim()});});
 form('#result-form',async(f,el)=>{const data={session_id:currentSession().id,revision:Number(el.dataset.revision),xp:numberValue(f.get('xp'),0,99),physical:numberValue(f.get('physical'),0,99),mental:numberValue(f.get('mental'),0,99),note:f.get('note').trim()};confirmAction('Saját eredmények áttekintése',`<div class="review"><p>Kapott XP: <strong>${data.xp}</strong></p><p>Új fizikai trauma: <strong>${data.physical}</strong></p><p>Új mentális trauma: <strong>${data.mental}</strong></p><p>${esc(data.note)}</p></div><p>Javításkor a korábbi eredményhez képesti különbözet kerül az adatlapra.</p>`,()=>mutation('save_result',data),'Eredmények mentése');});
 form('#common-form',async(f,el)=>mutation('save_common',{session_id:currentSession().id,revision:Number(el.dataset.revision),resolution:f.get('resolution').trim(),note:f.get('note').trim()}));
 form('#note-form',async f=>mutation('add_note',{session_id:currentSession().id,body:f.get('body').trim()}));
 form('#join-form',async f=>{const data=await rpc('join_campaign',Object.fromEntries(f),null);pendingInvite='';sessionStorage.removeItem('arkham.pendingInvite');history.replaceState({},'',location.pathname);dirty=false;page='overview';await loadCampaign(data.campaign_id);notify('Csatlakoztál a kampányhoz.');});
 form('#manual-invite',async f=>{let token=f.get('invite').trim();try{token=new URL(token).searchParams.get('invite')||token;}catch{}if(!/^[\da-f]{8}-(?:[\da-f]{4}-){3}[\da-f]{12}$/i.test(token))throw Error('Érvénytelen meghívókód.');pendingInvite=token;sessionStorage.setItem('arkham.pendingInvite',token);dirty=false;render();});}
function action(a){if(['overview','investigator','session','journal','team','history'].includes(a)){nav(a);return;}if(a==='new-campaign')newCampaign();if(a==='choose')chooseCharacter();if(a==='start')startSession();if(a==='gm')transferRole();if(a==='owner')transferRole(true);
 if(a==='refresh'){const refresh=async()=>{if(campaign)await loadCampaign(campaign.id);else await loadAccount();dirty=false;notify('Az adatok frissültek.');};if(dirty)confirmAction('Adatok frissítése','<p>A még nem mentett mezők helyére a legutóbbi mentés kerül.</p>',refresh,'Frissítés');else perform(refresh);}
 if(a==='invite')perform(async()=>{const d=await rpc('create_invite');await loadCampaign(campaign.id);modal(`<h2>Meghívólink elkészült</h2><p>A link 7 napig érvényes. Másold ki, és küldd el a társaságnak.</p>${field('invite-link','Meghívólink',inviteUrl(d.token),'text','readonly')}<button type="button" data-dismiss>Rendben</button>`);});
 if(a==='dismiss-invite'){pendingInvite='';sessionStorage.removeItem('arkham.pendingInvite');history.replaceState({},'',location.pathname);dirty=false;render();}
 if(a==='close-session')confirmAction('Alkalom lezárása','<p>Minden eredmény véglegessé válik. A következő alkalom új játékmesterrel is indulhat.</p>',()=>mutation('close_session',{session_id:currentSession().id}),'Alkalom lezárása');
 if(a==='close-campaign')confirmAction('Kampány lezárása','<p>A teljes napló megmarad, de a kampány többé nem szerkeszthető.</p>',()=>mutation('close_campaign'),'Kampány lezárása');
 if(a==='logout'){const leave=async()=>{const {error}=await db.auth.signOut();if(error)throw error;user=null;campaign=null;dirty=false;loadVersion++;$('#modal').close();render();};if(dirty)confirmAction('Kijelentkezés','<p>A nem mentett módosítások elvesznek.</p>',leave,'Kijelentkezés');else perform(leave);}}

function appendDeleteButton(){if(page!=='team'||!isOwner())return;const panel=[...document.querySelectorAll('.panel')].find(p=>p.querySelector('h2')?.textContent==='Kampány kezelése');if(!panel)return;const box=document.createElement('div');box.innerHTML='<hr><p class="muted">A végleges törlés eltávolítja a kampány minden adatát és nem vonható vissza.</p><button type="button" id="delete-campaign" class="ghost">Kampány végleges törlése</button>';panel.append(box);$('#delete-campaign').onclick=deleteCampaign;}
function deleteCampaign(){const id=campaign.id,name=campaign.name;modal(`<h2>Kampány végleges törlése</h2><p>Ez törli a kampányt, az alkalmakat, a nyomozói adatlapokat, az eredményeket, a meghívókat és a teljes naplót.</p><p class="muted">A megerősítéshez írd be pontosan: <strong>${esc(name)}</strong></p><form id="delete-campaign-form">${field('confirmation','Kampány neve','','text','required autocomplete="off"')}<div class="actions"><button type="submit" class="primary">Végleges törlés</button><button type="button" data-dismiss>Mégse</button></div></form>`);$('#delete-campaign-form').onsubmit=e=>{e.preventDefault();perform(async()=>{const confirmation=new FormData(e.target).get('confirmation').trim();if(confirmation!==name)throw Error('A megerősítéshez pontosan írd be a kampány nevét.');const {error}=await db.rpc('arkham_delete_campaign',{p_campaign:id,p_confirmation:confirmation});if(error)throw error;if(localStorage.getItem('arkham.selectedCampaign')===id)localStorage.removeItem('arkham.selectedCampaign');campaign=null;chosen=null;dirty=false;page='campaigns';await loadAccount();page='campaigns';render();$('#modal').close();notify('A kampány véglegesen törölve.');});};}

window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
window.addEventListener('offline',()=>notify('Nincs internetkapcsolat. A kitöltött mezők megmaradnak; kapcsolódás után próbáld újra a mentést.'));
window.addEventListener('online',()=>notify('Újra van internetkapcsolat. A mentést most újrapróbálhatod.'));
db.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'){user=session?.user;recovery=true;passwordView();}else if(event==='SIGNED_OUT'){user=null;campaign=null;loadVersion++;dirty=false;render();}else if(event==='TOKEN_REFRESHED'){user=session?.user||null;}});
async function boot(){root.innerHTML='<main class="auth"><div class="brand">◇ ARKHAM</div><p role="status">A kampánynapló betöltése…</p></main>';try{const {data,error}=await db.auth.getSession();if(error)throw error;user=data.session?.user||null;if(recovery&&user)passwordView();else if(user)await loadAccount();else authView();}catch(e){root.innerHTML=`<main class="auth"><section class="panel"><h1>Most nem sikerült kapcsolódni</h1><p class="error">${esc(errorText(e))}</p><button id="retry" class="primary">Újrapróbálás</button></section></main>`;$('#retry').onclick=boot;}}
boot();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_campaign_state',title:'Kampány állapota',description:'A bejelentkezett játékos által megnyitott kampány már betöltött állapotának olvasása.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(input&&Object.keys(input).length)throw Error('Nem vár paramétert.');if(!user||!campaign)throw Error('Nyiss meg egy kampányt bejelentkezés után.');return {campaign:campaign.name,session:currentSession(),players:members.map(m=>({name:m.name,investigator:character(investigators.find(i=>i.active&&i.user_id===m.user_id))?.name}))};}})).catch(()=>{});}catch{}}

function eventDetails(e){
 const before=e.detail.before||e.detail.previous||{},after=e.detail.after||e.detail.current||{};
 const labels={character_code:'Nyomozó',earned:'Összes kapott XP',spent:'Elköltött XP',xp:'Alkalom XP-je',physical:'Fizikai trauma',mental:'Mentális trauma',status:'Állapotok',notes:'Személyes jegyzet',note:'Alkalom jegyzete',deck:'Paklilink'};
 const rows=Object.entries(labels).filter(([k])=>(k in before||k in after)&&before[k]!==after[k]);
 return rows.map(([k,label])=>{const format=v=>k==='character_code'?(chars.find(c=>c.code===v)?.name||v||'—'):v??'—';return `<p><strong>${label}</strong><br><span class="muted">${esc(format(before[k]))}</span> → ${esc(format(after[k]))}</p>`;}).join('')||'<p>Az értékek nem változtak.</p>';
}
