-- Standard campaign investigators listed by Hall of Arkham, through The Drowned City,
-- plus the five Investigator Starter Deck investigators. Parallel and Barkham variants
-- are intentionally excluded because they are not separate standard-campaign identities.
insert into public.arkham_characters(code,name,class,subtitle) values
 ('roland','Roland Banks','Őrző','The Fed'),
 ('daisy','Daisy Walker','Kutató','The Librarian'),
 ('skids','“Skids” O’Toole','Zsivány','The Ex-Con'),
 ('agnes','Agnes Baker','Misztikus','The Waitress'),
 ('wendy','Wendy Adams','Túlélő','The Urchin'),
 ('zoey','Zoey Samaras','Őrző','The Chef'),
 ('rex','Rex Murphy','Kutató','The Reporter'),
 ('jenny','Jenny Barnes','Zsivány','The Dilettante'),
 ('jim','Jim Culver','Misztikus','The Musician'),
 ('ashcan_pete','“Ashcan” Pete','Túlélő','The Drifter'),
 ('mark','Mark Harrigan','Őrző','The Soldier'),
 ('minh','Minh Thi Phan','Kutató','The Secretary'),
 ('sefina','Sefina Rousseau','Zsivány','The Painter'),
 ('akachi','Akachi Onyele','Misztikus','The Shaman'),
 ('william_yorick','William Yorick','Túlélő','The Gravedigger'),
 ('lola','Lola Hayes','Semleges','The Actress'),
 ('leo','Leo Anderson','Őrző','The Expedition Leader'),
 ('ursula','Ursula Downs','Kutató','The Explorer'),
 ('finn','Finn Edwards','Zsivány','The Bootlegger'),
 ('father_mateo','Father Mateo','Misztikus','The Priest'),
 ('calvin','Calvin Wright','Túlélő','The Haunted'),
 ('carolyn','Carolyn Fern','Őrző','The Psychologist'),
 ('joe','Joe Diamond','Kutató','The Private Investigator'),
 ('preston','Preston Fairmont','Zsivány','The Millionaire'),
 ('diana','Diana Stanley','Misztikus','The Redeemed Cultist'),
 ('rita','Rita Young','Túlélő','The Athlete'),
 ('marie','Marie Lambeau','Misztikus','The Entertainer'),
 ('tommy','Tommy Muldoon','Őrző','The Rookie Cop'),
 ('mandy','Mandy Thompson','Kutató','The Researcher'),
 ('tony','Tony Morgan','Zsivány','The Bounty Hunter'),
 ('luke','Luke Robinson','Misztikus','The Dreamer'),
 ('patrice','Patrice Hathaway','Túlélő','The Violinist'),
 ('sister_mary','Sister Mary','Őrző','The Nun'),
 ('amanda','Amanda Sharpe','Kutató','The Student'),
 ('trish','Trish Scarborough','Zsivány','The Spy'),
 ('dexter','Dexter Drake','Misztikus','The Magician'),
 ('silas','Silas Marsh','Túlélő','The Sailor'),
 ('daniela','Daniela Reyes','Őrző','The Mechanic'),
 ('norman','Norman Withers','Kutató','The Astronomer'),
 ('monterey','Monterey Jack','Zsivány','The Archaeologist'),
 ('lily','Lily Chen','Misztikus','The Martial Artist'),
 ('bob','Bob Jenkins','Túlélő','The Salesman'),
 ('carson','Carson Sinclair','Őrző','The Butler'),
 ('vincent','Vincent Lee','Kutató','The Doctor'),
 ('kymani','Kymani Jones','Zsivány','The Security Consultant'),
 ('amina','Amina Zidane','Misztikus','The Operator'),
 ('darrell','Darrell Simmons','Túlélő','The Photographer'),
 ('charlie','Charlie Kane','Semleges','The Politician'),
 ('wilson','Wilson Richards','Őrző','The Handyman'),
 ('kate','Kate Winthrop','Kutató','The Scientist'),
 ('alessandra','Alessandra Zorzi','Zsivány','The Countess'),
 ('kohaku','Kohaku Narukami','Misztikus','The Folklorist'),
 ('hank','Hank Samson','Túlélő','The Farmhand'),
 ('marion','Marion Tavares','Őrző','The Trawler'),
 ('lucius','Lucius Galloway','Kutató','The Poet'),
 ('michael','Michael McGlen','Zsivány','The Gangster'),
 ('gloria','Gloria Goldberg','Misztikus','The Writer'),
 ('george','George Barnaby','Túlélő','The Lawyer'),
 ('agatha','Agatha Crane','Kutató / Misztikus','The Parapsychologist'),
 ('nathaniel','Nathaniel Cho','Őrző','The Boxer'),
 ('harvey','Harvey Walters','Kutató','The Professor'),
 ('winifred','Winifred Habbamock','Zsivány','The Aviatrix'),
 ('jacqueline','Jacqueline Fine','Misztikus','The Psychic'),
 ('stella','Stella Clark','Túlélő','The Letter Carrier')
on conflict (code) do update set
 name=excluded.name,class=excluded.class,subtitle=excluded.subtitle;
